services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/app
    depends_on:
      - db
    ports:
      - 3000:3000
    env_file:
      - path: ./.env

  db: 
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  db_data:
