---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/":
    get:
      summary: Listar pedidos em producao
      tags:
      - Producao
      responses:
        '200':
          description: lista de pedidos em producao
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
