---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/pedidos":
    get:
      summary: Listar pedidos em producao
      tags:
      - Producao
      responses:
        '200':
          description: lista de pedidos em producao
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pedido'
    post:
      summary: Enviar pedido para producao
      tags:
      - Producao
      parameters: []
      responses:
        '201':
          description: Pedido enviado para producao com sucesso
        '422':
          description: Unprocessable Entity
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                num_pedido:
                  type: integer
                  example: 1
                itens_attributes:
                  type: array
                  items:
                    $ref: '#/components/schemas/Item'
              required:
              - num_pedido
              - itens_attributes
        required: true
  "/pedidos/{num_pedido}":
    parameters:
    - name: num_pedido
      in: path
      description: Número do Pedido
      required: true
      schema:
        type: integer
    put:
      summary: Atualizar status do pedido
      tags:
      - Producao
      parameters:
      - name: status
        in: query
        description: Novo status do pedido
        required: true
        schema:
          $ref: '#/components/schemas/StatusPedido'
      responses:
        '200':
          description: Status do pedido atualizado com sucesso
        '404':
          description: Pedido não encontrado
        '422':
          description: Unprocessable Entity
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000

components:
  schemas:
    Pedido:
      type: object
      properties:
        id:
          type: integer
          description: Identificador local do pedido no sistema de produção
        num_pedido:
          type: string
          description: Número do pedido global
        status:
          $ref: '#/components/schemas/StatusPedido'
        itens:
          type: array
          items:
            $ref: '#/components/schemas/Item'
    Item:
      type: object
      properties:
        nome:
          type: string
          example: "X-Burger"
        observacao:
          type: string
          example: "Sem picles"
        quantidade:
          type: integer
          example: 4
    StatusPedido:
      type: string
      enum:
        - recebido
        - em_preparacao
        - pronto
        - finalizado
