on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf
        with:
          ruby-version: '3.2.2'
          bundler-cache: true

      - name: Run coverage
        env:
          COVERAGE: true
        run: |
          bundle exec rspec

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.organization=fiap-tech-challenge-soat1
            -Dsonar.projectKey=fiap-tech-challenge-soat1_fiap-tech-challenge-1-producao
            -Dsonar.sources=app/,lib/
            -Dsonar.language=ruby
            -Dsonar.exclusions=**/*_spec.rb,spec/**/*,config/**/*,vendor/**/*
            -Dsonar.coverageReportPaths=coverage/
            -Dsonar.verbose=true
            -Dsonar.qualitygate.wait=true
        env:
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}

      - name: Setup Docker
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Image
        run: docker build -t producao-service-tech-challenge:$GITHUB_SHA .
